// AUTH DISPATCH STATES

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
//PROFILE DISPATCH STATES
export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL';
export const  LOAD_USER_PROFILE_SUCCESS = ' LOAD_USER_PROFILE_SUCCESS';
export const  LOAD_USER_PROFILE_FAIL = ' LOAD_USER_PROFILE_FAIL';
export const LOAD_COURSE_DATA_SUCCESS='LOAD_COURSE_DATA_SUCCESS';
export const LOAD_COURSE_DATA_FAIL='LOAD_COURSE_DATA_FAIL';
export const DELETE_ASSIGNMENT_FAIL='DELETE_ASSIGNMENT_FAIL';
export const DELETE_ASSIGNMENT_SUCCESS='DELETE_ASSIGNMENT_SUCCESS';






